import { BiomarkerConfig } from './biomarkerConfig.types'

export const BIOMARKER_CONFIGS: Array<Partial<BiomarkerConfig>> = [
    {
        name: 'Glucose',
        ucumCode: 'mg/dL',
        description: 'Fasting blood glucose',
        order: 0,
        isDefault: true,
    },
    {
        name: 'Hemoglobin',
        ucumCode: 'g/dL',
        description: 'Oxygen-carrying protein in red blood cells',
        order: 1,
        isDefault: true,
    },
    {
        name: 'Total Cholesterol',
        ucumCode: 'mg/dL',
        description: 'Total blood cholesterol',
        order: 2,
        isDefault: true,
    },
    {
        name: 'HDL Cholesterol',
        ucumCode: 'mg/dL',
        description: 'High-density lipoprotein (good cholesterol)',
        order: 3,
        isDefault: true,
    },
    {
        name: 'LDL Cholesterol',
        ucumCode: 'mg/dL',
        description: 'Low-density lipoprotein (bad cholesterol)',
        order: 4,
        isDefault: true,
    },
    {
        name: 'Triglycerides',
        ucumCode: 'mg/dL',
        description: 'Type of fat in blood',
        order: 5,
        isDefault: true,
    },
    {
        name: 'TSH',
        ucumCode: 'u[iU]/mL',
        description: 'Thyroid Stimulating Hormone',
        order: 6,
        isDefault: true,
    },
    {
        name: 'ALT',
        ucumCode: 'U/L',
        description: 'Alanine Aminotransferase (liver enzyme)',
        order: 7,
        isDefault: true,
    },
    {
        name: 'AST',
        ucumCode: 'U/L',
        description: 'Aspartate Aminotransferase (liver enzyme)',
        order: 8,
        isDefault: true,
    },
    {
        name: 'Creatinine',
        ucumCode: 'mg/dL',
        description: 'Kidney function marker',
        order: 9,
        isDefault: true,
    },
    {
        name: 'White Blood Cells',
        ucumCode: '10*3/uL',
        description: 'Immune system cells',
        order: 10,
        isDefault: true,
    },
    {
        name: 'Red Blood Cells',
        ucumCode: '10*6/uL',
        description: 'Oxygen-carrying blood cells',
        order: 11,
        isDefault: true,
    },
    {
        name: 'Platelets',
        ucumCode: '10*3/uL',
        description: 'Blood clotting cells',
        order: 12,
        isDefault: true,
    },
    {
        name: 'Hematocrit',
        ucumCode: '%',
        description: 'Percentage of red blood cells in blood',
        order: 13,
        isDefault: true,
    },
    {
        name: 'MCV',
        ucumCode: 'fL',
        description: 'Mean Corpuscular Volume',
        order: 14,
        isDefault: true,
    },
    {
        name: 'MCH',
        ucumCode: 'pg',
        description: 'Mean Corpuscular Hemoglobin',
        order: 15,
        isDefault: true,
    },
    {
        name: 'MCHC',
        ucumCode: 'g/dL',
        description: 'Mean Corpuscular Hemoglobin Concentration',
        order: 16,
        isDefault: true,
    },
    {
        name: 'RDW',
        ucumCode: '%',
        description: 'Red Cell Distribution Width',
        order: 17,
        isDefault: true,
    },
    {
        name: 'Vitamin D',
        ucumCode: 'ng/mL',
        description: '25-hydroxyvitamin D',
        order: 18,
        isDefault: true,
    },
    {
        name: 'Vitamin B12',
        ucumCode: 'pg/mL',
        description: 'Cobalamin',
        order: 19,
        isDefault: true,
    },
    {
        name: 'Iron',
        ucumCode: 'ug/dL',
        description: 'Serum iron',
        order: 20,
        isDefault: true,
    },
    {
        name: 'Ferritin',
        ucumCode: 'ng/mL',
        description: 'Iron storage protein',
        order: 21,
        isDefault: true,
    },
    {
        name: 'Folate',
        ucumCode: 'ng/mL',
        description: 'Vitamin B9',
        order: 22,
        isDefault: true,
    },
    {
        name: 'Blood urea nitrogen',
        ucumCode: 'mg/dL',
        description: 'Blood urea nitrogen (BUN)',
        order: 23,
        isDefault: true,
    },
    {
        name: 'Uric Acid',
        ucumCode: 'mg/dL',
        description: 'Purine metabolism marker',
        order: 24,
        isDefault: true,
    },
    {
        name: 'Total Protein',
        ucumCode: 'g/dL',
        description: 'Total serum protein',
        order: 25,
        isDefault: true,
    },
    {
        name: 'Albumin',
        ucumCode: 'g/dL',
        description: 'Major blood protein',
        order: 26,
        isDefault: true,
    },
    {
        name: 'Bilirubin',
        ucumCode: 'mg/dL',
        description: 'Total bilirubin',
        order: 27,
        isDefault: true,
    },
    {
        name: 'Alkaline Phosphatase',
        ucumCode: 'U/L',
        description: 'ALP (liver/bone enzyme)',
        order: 28,
        isDefault: true,
    },
    {
        name: 'GGT',
        ucumCode: 'U/L',
        description: 'Gamma-Glutamyl Transferase',
        order: 29,
        isDefault: true,
    },
    {
        name: 'HbA1c',
        ucumCode: '%',
        description: 'Glycated hemoglobin (diabetes marker)',
        order: 30,
        isDefault: true,
    },
    {
        name: 'Sodium',
        ucumCode: 'meq/L',
        description: 'Blood sodium',
        order: 31,
        isDefault: true,
    },
    {
        name: 'Potassium',
        ucumCode: 'meq/L',
        description: 'Blood potassium',
        order: 32,
        isDefault: true,
    },
    {
        name: 'Chloride',
        ucumCode: 'meq/L',
        description: 'Blood chloride',
        order: 33,
        isDefault: true,
    },
    {
        name: 'Calcium',
        ucumCode: 'mg/dL',
        description: 'Blood calcium',
        order: 34,
        isDefault: true,
    },
    {
        name: 'Magnesium',
        ucumCode: 'mg/dL',
        description: 'Blood magnesium',
        order: 35,
        isDefault: true,
    },
    {
        name: 'Phosphorus',
        ucumCode: 'mg/dL',
        description: 'Blood phosphorus',
        order: 36,
        isDefault: true,
    },
    {
        name: 'CRP',
        ucumCode: 'mg/L',
        description: 'C-Reactive Protein (inflammation marker)',
        order: 37,
        isDefault: true,
    },
    {
        name: 'ESR',
        ucumCode: 'mm/h',
        description: 'Erythrocyte Sedimentation Rate',
        order: 38,
        isDefault: true,
    },
    {
        name: 'PSA',
        ucumCode: 'ng/mL',
        description: 'Prostate-Specific Antigen',
        order: 39,
        isDefault: true,
    },
]
